// create Course object
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Mvc.Models
{
    public class Course
    {
        // primary key values are provided by the user rather than generated by the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        [Display(Name = "Number")]          // text box caption is Number
        public int CourseID { get; set; }   // course's ID

        [StringLength(50, MinimumLength = 3)]   // string length between 3 and 50
        public string Title { get; set; }       // title of course

        [Range(0,5)]                            // credits between 0 and 5
        public int Credits { get; set; }        // number of credits of course

        public int DepartmentID { get; set; }   // ID of department associated with course

        public Department Department { get; set; }  // department associated with course

        public ICollection<Enrollment> Enrollments { get; set; } // who's enrolled in the course

        public ICollection<CourseAssignment> CourseAssignments { get; set; } // collection of teachers teaching the course
    }
}
